### ISSUE TITLE
EDK2 MrChromebox UefiPayloadPkg build fails with an error.

### ISSUE THREAD

**Issue by dponamorev1976** [MrChromebox/firmware#892]
EDK2 MrChromebox origin/uefipayload_2511 branch. I'm trying to compile a separate module UefiPayloadPkg.

In mrchromebox directory$ 

**. edksetup.sh** 

then  

**build -p UefiPayloadPkg/UefiPayloadPkg.dsc -t GCC5 -a X64**

The module UefiPayloadPkg compilation fails with an error:

_/home/ipc/work/coreboot/payloads/external/edk2/workspace/mrchromebox/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c: In function ‘BuildHobFromBl’:
/home/ipc/work/coreboot/payloads/external/edk2/workspace/mrchromebox/UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c:489:27: error: passing argument 1 of ‘ParseCapsules’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  489 |   Status = ParseCapsules (BuildCvHob);_
  
Full compilation log in the file build.log
[build.log](https://github.com/user-attachments/files/25762789/build.log)

This does not happen when compiling a UefiPayloadPkg module from tianocore/EDK2 branch.

**Comment by MrChromebox** [comment]
does it build from coreboot? If so, just do that. I've never tested building outside of coreboot or with various host toolchains

**Comment by dponamorev1976** [comment]
> does it build from coreboot? If so, just do that. I've never tested building outside of coreboot or with various host toolchains

No, the build is not specifically from the mrchromebox edk2 directory. The entire coreboot + edk2 build works fine. Sometimes you just need to tweak something in the edk2 and compile independently of the rest of coreboot. As far as I understand from the answer, for example, different versions of GCC are used, and this leads to warnings and errors? Or is it a matter of configuration files? 
It's very inconvenient to compile the entire project when changes are made to the edk2 package.

This sequence in the mrchromebox edk2 directory also doesn't lead to success :

_git submodule update --init
make -C BaseTools
. edksetup.sh
build -p UefiPayloadPkg/UefiPayloadPkg.dsc -t GCC5 -a X64_

**Comment by MrChromebox** [comment]
> build -p UefiPayloadPkg/UefiPayloadPkg.dsc -t GCC5 -a X64

you do realize that the coreboot build command is much longer, and that yours will not produce a usable image
